import type { Metadata } from "next";
import { Playwrite_AR, Space_Grotesk, Tiny5 } from "next/font/google";
import "./globals.css";
import { NavBottomBar } from "@/components/nav-bottomBar";
import { Header } from "@/components/header";

const CursiveHeading = Playwrite_AR({
	weight: "400", // Added a valid property
	variable: "--font-cursive-heading",
});

const tiny5 = Tiny5({
	subsets: ["latin"],
	weight: "400", // Added a valid property
	variable: "--font-tiny5",
});

const spaceGrotesk = Space_Grotesk({
	subsets: ["latin"],
	variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
	title: "Converter Site",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${CursiveHeading.variable} ${tiny5.variable} ${spaceGrotesk.variable} antialiased`}
			>
				<div className="p-5 min-h-dvh flex flex-col justify-center items-center">
					<div className="sticky top-5">
						<Header />
					</div>
					<div className="flex-grow">{children}</div>
					<div className="sticky bottom-5">
						<NavBottomBar />
					</div>
				</div>
			</body>
		</html>
	);
}
